/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: smooth998 (https://sketchfab.com/smooth998)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/low-poly-city-night-885d8034bc02407fb48cf7f0dfe61d67
Title: Low-poly City Night
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function CityModel(props) {
  const { nodes, materials } = useGLTF("/city/Sketchfab_Scene.glb");
  return (
    <group {...props} dispose={null} scale={3}>
      <group position={[0.071, 0.001, -0.697]} scale={20}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_178001.geometry}
          material={materials[".001"]}
          position={[0.074, -0.013, 0.053]}
        />
      </group>
      <group position={[1.879, -0.003, 1.899]} />
      <group
        position={[0.617, -0.002, 0.388]}
        rotation={[0, -1.571, 0]}
        scale={0.936}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_45.geometry}
          material={materials.material}
          position={[0.047, 0.267, 0.034]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_46.geometry}
          material={materials.logos}
          position={[0.085, 0.543, -0.024]}
        />
      </group>
      <group position={[-0.107, 0.002, -1.108]} scale={1.298}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_16.geometry}
          material={materials.material}
          position={[-0.043, 0.831, -0.026]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_17.geometry}
          material={materials.red_light}
          position={[-0.032, 1.476, -0.038]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_18.geometry}
          material={materials.logos}
          position={[-0.082, 1.644, -0.007]}
        />
      </group>
      <group position={[0.14, 0.001, -0.487]} rotation={[Math.PI, 0, Math.PI]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_12.geometry}
          material={materials.material}
          position={[0, 0.636, 0.028]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_13.geometry}
          material={materials.red_light}
          position={[0.001, 1.102, 0.028]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_14.geometry}
          material={materials.logos}
          position={[0.105, 1.205, -0.136]}
        />
      </group>
      <group
        position={[-0.699, 0.341, 0.456]}
        rotation={[0, 1.571, 0]}
        scale={1.496}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_20.geometry}
          material={materials.material}
          position={[0, 0.126, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_21.geometry}
          material={materials.red_light}
          position={[0, 0.431, -0.001]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_22.geometry}
          material={materials.logos}
          position={[0.064, 0.406, 0.112]}
        />
      </group>
      <group position={[0.179, 0.003, 0.043]} scale={0.726}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_24.geometry}
          material={materials.material}
          position={[0, 0.581, 0.024]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_25.geometry}
          material={materials.red_light}
          position={[0, 1.149, 0.026]}
        />
      </group>
      <group position={[1.059, -0.003, -0.792]} scale={2.346}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_27.geometry}
          material={materials.material}
          position={[0.032, 0.194, 0.004]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_28.geometry}
          material={materials.red_light}
          position={[0.028, 0.365, 0.004]}
        />
      </group>
      <group position={[0.747, 0.287, -1.218]} scale={1.463}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_36.geometry}
          material={materials.material}
          position={[0, 0.719, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_37.geometry}
          material={materials.red_light}
          position={[0, 1.356, 0]}
        />
      </group>
      <group position={[-0.358, 0, 0.894]} scale={[0.575, 0.55, 0.575]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_30.geometry}
          material={materials.material}
          position={[0, 0.363, 0.043]}
        />
      </group>
      <group position={[1.034, 0, -0.161]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_32.geometry}
          material={materials.material}
          position={[-0.063, 0.38, 0.001]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_33.geometry}
          material={materials.red_light}
          position={[-0.064, 0.743, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_34.geometry}
          material={materials.logos}
          position={[-0.119, 0.711, 0.119]}
        />
      </group>
      <group
        position={[-1.731, 0.005, 0.877]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[1.471, 1.849, 1.471]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_48.geometry}
          material={materials.material}
          position={[0, 0.385, 0.017]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_49.geometry}
          material={materials.red_light}
          position={[0, 0.771, 0.017]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_50.geometry}
          material={materials.logos}
          position={[0.001, 0.716, -0.033]}
        />
      </group>
      <group position={[-1.234, -0.002, 0.425]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_41.geometry}
          material={materials.material}
          position={[0.001, 0.9, -0.001]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_43.geometry}
          material={materials.logos}
          position={[-0.005, 1.765, 0.005]}
        />
      </group>
      <group position={[0.869, 0.001, 0.851]} scale={[0.057, 0.103, 0.057]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_39.geometry}
          material={materials.material}
          position={[0.727, 0.993, 0.741]}
        />
      </group>
      <group position={[1.567, 0, 0.296]} scale={[0.575, 0.55, 0.575]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_52.geometry}
          material={materials.material}
          position={[0, 0.363, 0.043]}
        />
      </group>
      <group
        position={[-0.419, -0.001, 1.439]}
        rotation={[0, 1.571, 0]}
        scale={1.263}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_54.geometry}
          material={materials.material}
          position={[-0.018, 0.18, 0.025]}
        />
      </group>
      <group
        position={[0.285, 0, 0.854]}
        rotation={[0, 1.571, 0]}
        scale={0.096}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_59.geometry}
          material={materials.material}
          position={[0, 3.921, 0]}
        />
      </group>
      <group position={[-1.038, -0.128, 0.883]} scale={[0.9, 0.834, 0.9]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_61.geometry}
          material={materials.material}
          position={[0, 0.382, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_62.geometry}
          material={materials.red_light}
          position={[-0.001, 0.75, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_63.geometry}
          material={materials.logos}
          position={[-0.045, 0.718, 0.142]}
        />
      </group>
      <group
        position={[1.202, -0.001, 0.826]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={1.263}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_65.geometry}
          material={materials.material}
          position={[-0.018, 0.18, 0.025]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_66.geometry}
          material={materials.logos}
          position={[-0.134, 0.336, 0.032]}
        />
      </group>
      <group
        position={[-0.318, -0.001, 0.426]}
        rotation={[0, 1.571, 0]}
        scale={1.263}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_162.geometry}
          material={materials.material}
          position={[-0.018, 0.18, 0.025]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_163.geometry}
          material={materials.logos}
          position={[-0.134, 0.336, 0.032]}
        />
      </group>
      <group
        position={[1.989, 0, -0.498]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.639, 0.611, 0.639]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_183.geometry}
          material={materials.material}
          position={[0, 0.363, 0.043]}
        />
      </group>
      <group position={[1.199, 0.001, 0.076]} scale={[0.259, 0.443, 0.24]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_289.geometry}
          material={materials["1.001"]}
          position={[-3.215, 0.583, 4.098]}
        />
      </group>
      <group position={[0.595, 0, 0.031]} scale={[0.9, 0.834, 0.9]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_4.geometry}
          material={materials.material}
          position={[0, 0.382, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6.geometry}
          material={materials.logos}
          position={[-0.045, 0.718, 0.142]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_68.geometry}
        material={materials.material_3}
        position={[0.748, 0.003, 0.708]}
        scale={[1, 1, 1.425]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_70.geometry}
        material={materials.material_3}
        position={[0.422, 0.003, -0.673]}
        scale={[1, 1, 1.17]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_72.geometry}
        material={materials.material_3}
        position={[-0.123, 0.003, 0.105]}
        scale={[1, 1, 0.409]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_74.geometry}
        material={materials.material_3}
        position={[-0.533, 0.003, 0.174]}
        scale={[1, 1, 0.93]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_76.geometry}
        material={materials.material_3}
        position={[-0.868, 0.003, 2.075]}
        scale={[1, 1, 0.749]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_78.geometry}
        material={materials.material_3}
        position={[-1.415, 0.003, 1.3]}
        scale={[1, 1, 1.449]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_80.geometry}
        material={materials.material_3}
        position={[-1.962, 0.003, 1.875]}
        scale={[1, 1, 0.636]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_82.geometry}
        material={materials.material_3}
        position={[3.026, 0.003, 1.502]}
        scale={[1, 1, 0.887]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_84.geometry}
        material={materials.material_3}
        position={[2.7, 0.003, 0.021]}
        scale={[1, 1, 0.787]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_86.geometry}
        material={materials.material_3}
        position={[2.154, 0.003, 0.827]}
        scale={[1, 1, 0.619]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_88.geometry}
        material={materials.material_3}
        position={[1.744, 0.003, 1.896]}
        scale={[1, 1, 0.846]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_90.geometry}
        material={materials.material_3}
        position={[1.41, 0.003, 0.403]}
        scale={[1, 1, 0.913]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_92.geometry}
        material={materials.material_3}
        position={[-0.212, 0.003, -0.32]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[1, 1, 1.183]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_94.geometry}
        material={materials.material_3}
        position={[-0.157, 0.003, 0.205]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[1, 1, 1.272]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_96.geometry}
        material={materials.material_3}
        position={[1.182, 0.003, 0.638]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[1, 1, 1.303]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_98.geometry}
        material={materials.material_3}
        position={[-0.354, 0.003, 1.038]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[1, 1, 1.251]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_100.geometry}
        material={materials.material_3}
        position={[-0.466, 0.003, 1.287]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[1, 1, 1.201]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_102.geometry}
        material={materials.material_3}
        position={[0.126, 0.003, 1.758]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[1, 1, 1.147]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_104.geometry}
        material={materials.material_3}
        position={[1.173, 0.003, 2.222]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[1, 1, 1.235]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_106.geometry}
        material={materials.material_3}
        position={[0.34, 0.003, -2.711]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[1, 1, 1.094]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_108.geometry}
        material={materials.material_3}
        position={[1.265, 0.003, -2.173]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[1, 1, 1.473]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_110.geometry}
        material={materials.material_3}
        position={[0.185, 0.003, -1.743]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[1, 1, 1.045]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_112.geometry}
        material={materials.material_3}
        position={[0.144, 0.003, -1.487]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[1, 1, 1.067]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_114.geometry}
        material={materials.material_3}
        position={[0.244, 0.003, -0.937]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[1, 1, 1.111]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_8.geometry}
        material={materials.material}
        position={[0, 0.729, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_9.geometry}
        material={materials.logos}
        position={[-0.146, 1.371, 0.129]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_10.geometry}
        material={materials.red_light}
        position={[0.002, 1.445, 0.001]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_165.geometry}
        material={materials.material}
        position={[0.032, 0.194, 0.004]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_166.geometry}
        material={materials.red_light}
        position={[0.028, 0.365, 0.004]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_168.geometry}
        material={materials.material}
        position={[0, 0.729, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_169.geometry}
        material={materials.logos}
        position={[-0.146, 1.371, 0.129]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_170.geometry}
        material={materials.red_light}
        position={[0.002, 1.445, 0.001]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_172.geometry}
        material={materials.material}
        position={[0, 0.382, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_174.geometry}
        material={materials.logos}
        position={[-0.045, 0.718, 0.142]}
      />
    </group>
  );
}

useGLTF.preload("/city/Sketchfab_Scene.glb");
