/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function JumpAnimation({ setTriggerAnimation }) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    "/jump/animations/jump/6880bf1044fce83e052a4028_jump.glb"
  );
  const { actions } = useAnimations(animations, group);
  const animationName = "rig|rig|jump|rig|jump";

  function playOnce() {
    const action = actions[animationName];
    if (!action) return;
    const duration = action.getClip().duration;
    action.reset().play();
    setTimeout(() => {
      action.stop();
    }, duration * 1000);
  }

  useEffect(() => {
    setTriggerAnimation(() => playOnce);
  }, []);

  return (
    <group ref={group} scale={[0.1, 0.1, 0.1]} dispose={null}>
      <group name="Scene">
        <group name="rig" rotation={[Math.PI / 2, 0, 0]}>
          <group name="6880bf1044fce83e052a4028">
            <skinnedMesh
              name="6880bf1044fce83e052a4028_1"
              geometry={nodes["6880bf1044fce83e052a4028_1"].geometry}
              material={materials["Wolf3D_Eye.001"]}
              skeleton={nodes["6880bf1044fce83e052a4028_1"].skeleton}
            />
            <skinnedMesh
              name="6880bf1044fce83e052a4028_2"
              geometry={nodes["6880bf1044fce83e052a4028_2"].geometry}
              material={materials["Wolf3D_Skin.001"]}
              skeleton={nodes["6880bf1044fce83e052a4028_2"].skeleton}
            />
            <skinnedMesh
              name="6880bf1044fce83e052a4028_3"
              geometry={nodes["6880bf1044fce83e052a4028_3"].geometry}
              material={materials["Wolf3D_Teeth.001"]}
              skeleton={nodes["6880bf1044fce83e052a4028_3"].skeleton}
            />
            <skinnedMesh
              name="6880bf1044fce83e052a4028_4"
              geometry={nodes["6880bf1044fce83e052a4028_4"].geometry}
              material={materials["Wolf3D_Hair.001"]}
              skeleton={nodes["6880bf1044fce83e052a4028_4"].skeleton}
            />
            <skinnedMesh
              name="6880bf1044fce83e052a4028_5"
              geometry={nodes["6880bf1044fce83e052a4028_5"].geometry}
              material={materials["Wolf3D_Outfit_Top.001"]}
              skeleton={nodes["6880bf1044fce83e052a4028_5"].skeleton}
            />
            <skinnedMesh
              name="6880bf1044fce83e052a4028_6"
              geometry={nodes["6880bf1044fce83e052a4028_6"].geometry}
              material={materials["Wolf3D_Outfit_Bottom.001"]}
              skeleton={nodes["6880bf1044fce83e052a4028_6"].skeleton}
            />
            <skinnedMesh
              name="6880bf1044fce83e052a4028_7"
              geometry={nodes["6880bf1044fce83e052a4028_7"].geometry}
              material={materials["Wolf3D_Outfit_Footwear.001"]}
              skeleton={nodes["6880bf1044fce83e052a4028_7"].skeleton}
            />
            <skinnedMesh
              name="6880bf1044fce83e052a4028_8"
              geometry={nodes["6880bf1044fce83e052a4028_8"].geometry}
              material={materials["Wolf3D_Body.001"]}
              skeleton={nodes["6880bf1044fce83e052a4028_8"].skeleton}
            />
          </group>
          <primitive object={nodes.root} />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("./jump/animations/jump/6880bf1044fce83e052a4028_jump.glb");
