/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Loïc Norgeot (https://sketchfab.com/norgeotloic)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/need-some-space-d6521362b37b48e3a82bce4911409303
Title: Need some space?
*/

import { useGLTF } from "@react-three/drei";
import { useEffect } from "react";
import * as THREE from "three";

export function SpaceModel(props) {
  const { nodes, materials } = useGLTF("/space/need_some_space.glb");

  useEffect(() => {
    const geometry = nodes.Object_2.geometry;
    const colors = geometry.attributes.color;
    console.log(colors);
    const arr = colors.array;

    for (let i = 0; i < arr.length; i++) {
      arr[i] = Math.min(Math.pow(arr[i], 0.6) * 2.2, 1.0);
    }

    colors.needsUpdate = true;
  }, []);
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.013}>
        <points geometry={nodes.Object_2.geometry}>
          <pointsMaterial
            size={0.01}
            sizeAttenuation
            transparent
            blending={THREE.AdditiveBlending}
            depthWrite={false}
            vertexColors
            opacity={0.5}
          />
        </points>
      </group>
    </group>
  );
}

useGLTF.preload("/space/need_some_space.glb");
