/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Loïc Norgeot (https://sketchfab.com/norgeotloic)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/need-some-space-d6521362b37b48e3a82bce4911409303
Title: Need some space?
*/

import { useGLTF } from "@react-three/drei";
import { useEffect, useState } from "react";
import * as THREE from "three";

export function SpaceModel(props) {
  const { nodes } = useGLTF("/space/need_some_space.glb");
  const [optimizedGeometry, setOptimizedGeometry] = useState(null);

  useEffect(() => {
    const sourceGeo = nodes.Object_2.geometry;
    const pos = sourceGeo.attributes.position;
    const col = sourceGeo.attributes.color;

    const pointCount = pos.count;
    const isMobile = /Mobi|Android/i.test(navigator.userAgent);

    const step = isMobile ? 5 : 2; // renders every X points on different devices

    const newPositions = [];
    const newColors = [];

    for (let i = 0; i < pointCount; i += step) {
      newPositions.push(pos.getX(i), pos.getY(i), pos.getZ(i));
      if (col) {
        newColors.push(col.getX(i), col.getY(i), col.getZ(i));
      }
    }

    const geometry = new THREE.BufferGeometry();
    geometry.setAttribute(
      "position",
      new THREE.Float32BufferAttribute(newPositions, 3)
    );

    if (col) {
      geometry.setAttribute(
        "color",
        new THREE.Float32BufferAttribute(newColors, 3)
      );
    }

    setOptimizedGeometry(geometry);
  }, [nodes]);

  if (!optimizedGeometry) return null;

  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.013}>
        <points geometry={optimizedGeometry}>
          <pointsMaterial
            size={0.01}
            sizeAttenuation={false}
            transparent
            blending={THREE.NormalBlending}
            depthWrite={false}
            vertexColors
            opacity={0.5}
          />
        </points>
      </group>
    </group>
  );
}

useGLTF.preload("/space/need_some_space.glb");
